kind: Pod
apiVersion: v1
metadata:
  name: annotations
  annotations:
    imageregistry: "https://hub.dokcer.com"
    buildURL: "https://jenkins.joindevops.com/expnese/backend/build/67"
spec:
  containers:
  - name: nginx
    image: nginx