apiVersion: v1
kind: service
metadata:
metadata:
  name: nginx
spec:
  selector:
    project: expense
    module: backend
    environment: dev
  port:
  - name: nginx-svc-port
    protocol: TCP
    port: 80 #service port
    targetPort: 80 #container port  